services:
  - type: web
    name: nitro-app
    env: node
    buildCommand: pnpm install && pnpm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./dev.db
      - key: JWT_SECRET
        value: supersecuresecretkey
      - key: RESEND_API_KEY
        value: re_49HPW5FC_2StBWtRfHfR4AqoRtF7aNQRm